name = "mysverse-roleplay-names"
main = "src/worker.ts"
compatibility_date = "2024-04-15"
workers_dev = true
kv_namespaces = [
    { binding = "MY_CACHE", id = "60f55bb7aa9045398e3392b42a07caba" },
]

[vars]
TRELLO_BOARD_ID = "657ac305962ed485a7d7cff4"
